### ISSUE TITLE
required modules

### ISSUE THREAD

**Issue by Markov-ctrl** [De-Technocrats/findigo#1]
please add a module name 'packaging' in the requirements.txt file

![Screenshot_20230415_074250_Termux](https://user-images.githubusercontent.com/126974442/232171349-0c748550-a3c6-4c24-b91a-4351f42f80bc.png)

**Comment by galihap76** [comment]
> please add a module name 'packaging' in the requirements.txt file
> 
> ![Screenshot_20230415_074250_Termux](https://user-images.githubusercontent.com/126974442/232171349-0c748550-a3c6-4c24-b91a-4351f42f80bc.png)

Hi, thank you for your issue. I was already put on packaging module in findigo tool and you can see on the link [here](https://github.com/De-Technocrats/findigo/blob/main/requirements.txt).
